name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  ci:
    name: Run CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Determine Go cache paths
        id: golang-path
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        shell: bash

      - name: Setup Go cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.golang-path.outputs.build }}
            ${{ steps.golang-path.outputs.module }}
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Run tests
        run: make ci
